Table Users
{
    ID int [pk, increment]
    Username varchar(255)
    PasswordHash varchar(255)
    PostalCode varchar(20)
    Balance double
    CreatedAt datetime
    UpdatedAt datetime
}

Table PrivateCustomer {
    UserID int [ref: - Users.ID]
    CPR varchar(20)
    CreatedAt datetime
    UpdatedAt datetime
}

Table BusinessCustomer {
    UserID int [ref: - Users.ID]
    CVR varchar(20)
    Credit double
    CreatedAt datetime
    UpdatedAt datetime
}

enum FuelType {
    Petrol
    Diesel
    Electric
    Hydrogen
}

enum EnergyClass {
    A
    B
    C
    D
}

enum LicenceType {
    A
    B
    C
    D
    BE
    CE
    DE
}

Table Vehicle
{
    ID int [pk, increment]
    Name varchar(255)
    Kilometers double
    ReleaseYear int
    BasePrice double
    TowBar bool
    EngineSize double
    KmPerLiter double
    LicenceType LicenceType
    FuelType FuelType
    CreatedAt datetime
    UpdatedAt datetime
}

Table HeavyVehicle {
    VehicleID int [ref: - Vehicle.ID]
    Weight double
    Height double
    Length double
    CreatedAt datetime
    UpdatedAt datetime
}

Table Truck {
    VehicleID int [ref: - Vehicle.ID]
    CargoCapacity double
    CreatedAt datetime
    UpdatedAt datetime
}

Table Bus {
    VehicleID int [ref: - Vehicle.ID]
    SeatCount int
    BedCount int
    Toilet bool
    CreatedAt datetime
    UpdatedAt datetime
}

Table Car {
    VehicleID int [ref: - Vehicle.ID]
    SeatCount int
    CreatedAt datetime
    UpdatedAt datetime
}

Table BusinessCar {
    VehicleID int [ref: - Vehicle.ID]
    CargoCapacity double
    RollCage bool
    CreatedAt datetime
    UpdatedAt datetime
}

Table PrivateCar {
    VehicleID int [ref: - Vehicle.ID]
    Isofix bool
    CreatedAt datetime
    UpdatedAt datetime
}

Table Auctions
{
    ID int [pk, increment]
    Seller int [ref: > Users.ID]
    VehicleID int [ref: - Vehicle.ID]
    MinimumPrice double
    CreatedAt datetime
    UpdatedAt datetime
}