Table Users
{
    ID int [pk, increment]
    Username varchar(255)
    PasswordHash varchar(255)
    PostalCode varchar(20)
    Balance double
    CreatedAt datetime
    UpdatedAt datetime
}

Table PrivateCustomers {
    UserID int [ref: - Users.ID]
    CPR varchar(20)
    CreatedAt datetime
    UpdatedAt datetime
}

Table BusinessCustomers {
    UserID int [ref: - Users.ID]
    CVR varchar(20)
    Credit double
    CreatedAt datetime
    UpdatedAt datetime
}

enum FuelType {
    Petrol
    Diesel
    Electric
    Hydrogen
}

enum EnergyClass {
    A
    B
    C
    D
}

enum LicenceType {
    A
    B
    C
    D
    BE
    CE
    DE
}

Table Vehicles
{
    ID int [pk, increment]
    Name varchar(255)
    Kilometers double
    ReleaseYear int
    BasePrice double
    TowBar bool
    EngineSize double
    KmPerLiter double
    LicenceType LicenceType
    FuelType FuelType
    CreatedAt datetime
    UpdatedAt datetime
}

Table HeavyVehicles {
    VehiclesID int [ref: - Vehicles.ID]
    Weight double
    Height double
    Length double
    CreatedAt datetime
    UpdatedAt datetime
}

Table SemiTrucks {
    VehiclesID int [ref: - Vehicles.ID]
    CargoCapacity double
    CreatedAt datetime
    UpdatedAt datetime
}

Table Buses {
    VehiclesID int [ref: - Vehicles.ID]
    SeatCount int
    BedCount int
    Toilet bool
    CreatedAt datetime
    UpdatedAt datetime
}

Table Cars {
    VehiclesID int [ref: - Vehicles.ID]
    SeatCount int
    CreatedAt datetime
    UpdatedAt datetime
}

Table BusinessCars {
    VehiclesID int [ref: - Vehicles.ID]
    CargoCapacity double
    RollCage bool
    CreatedAt datetime
    UpdatedAt datetime
}

Table PrivateCars {
    VehiclesID int [ref: - Vehicles.ID]
    Isofix bool
    CreatedAt datetime
    UpdatedAt datetime
}

Table Auctions
{
    ID int [pk, increment]
    Seller int [ref: > Users.ID]
    VehiclesID int [ref: - Vehicles.ID]
    MinimumPrice double
    CreatedAt datetime
    UpdatedAt datetime
}