CREATE TABLE users (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    balance DECIMAL(18, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_customers (
    user_id INT PRIMARY KEY REFERENCES users(id),
    cvr VARCHAR(20) NOT NULL,
    credit DECIMAL(18, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE private_customers (
    user_id INT PRIMARY KEY REFERENCES users(id),
    cpr VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auctions (
    id INT IDENTITY(1,1) PRIMARY KEY,
    seller_id INT NOT NULL REFERENCES users(id),
    vehicle_id INT NOT NULL REFERENCES vehicles(id),
    minimum_price DECIMAL(18, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bids (
    id INT IDENTITY(1,1) PRIMARY KEY,
    auction_id INT NOT NULL REFERENCES auctions(id),
    bidder_id INT NOT NULL REFERENCES users(id),
    amount DECIMAL(18, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE LicenceType AS ENUM ('A','B','C','D','BE','CE','DE');

CREATE TYPE FuelType AS ENUM ('Diesel','Petrol','Electric','Hydrogen');

CREATE TABLE vehicles (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    kilometers DOUBLE PRECISION NOT NULL,
    release_year INT NOT NULL,
    base_price DECIMAL(18, 2) NOT NULL,
    tow_bar BOOLEAN NOT NULL,
    engine_size DOUBLE PRECISION NOT NULL,
    km_per_liter DOUBLE PRECISION,
    licence_type LicenceType NOT NULL,
    fuel_type FuelType NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE heavy_vehicles (
    vehicle_id INT PRIMARY KEY REFERENCES vehicles(id),
    weight DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    length DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE semi_trucks (
    vehicle_id INT PRIMARY KEY REFERENCES vehicles(id),
    cargo_capacity DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE buses (
    vehicle_id INT PRIMARY KEY REFERENCES vehicles(id),
    seat_count INT NOT NULL,
    bed_count INT NOT NULL,
    toilet BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cars (
    vehicle_id INT PRIMARY KEY REFERENCES vehicles(id),
    seat_count INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_cars (
    vehicle_id INT PRIMARY KEY REFERENCES vehicles(id),
    cargo_capacity DOUBLE PRECISION NOT NULL,
    roll_cage BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE private_cars (
    vehicle_id INT PRIMARY KEY REFERENCES vehicles(id),
    isofix BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);